openapi: 3.0.3
info:
  description: VAST Management API definition
  title: VAST API Swagger Schema activedirectory settingsdiff API
  version: '1.0'
security:
- ApiToken: []
tags:
- name: settingsdiff
paths:
  /settingsdiff/:
    get:
      description: This endpoint lists system settings diff.
      operationId: settingsdiff_list
      parameters:
      - in: query
        name: page
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SettingsDiff'
                title: System Settings diff
                type: array
          description: System Settings diff information
      summary: System Settings Diff
      tags:
      - settingsdiff
components:
  schemas:
    SettingsDiff:
      properties:
        actual:
          type: string
        default:
          type: string
        guid:
          type: string
        id:
          type: integer
          x-cli-header: ID
        name:
          type: string
        type:
          type: string
      type: object
  securitySchemes:
    ApiToken:
      description: Send current valid API token in an Authorization header with format Api-Token <token>.
      in: header
      name: ApiToken
      type: apiKey
    basicAuth:
      description: Basic authentication using VMS user name and password
      scheme: basic
      type: http
