openapi: 3.0.3
info:
  description: VAST Management API definition
  title: VAST API Swagger Schema activedirectory openfilesqueries API
  version: '1.0'
security:
- ApiToken: []
tags:
- name: openfilesqueries
paths:
  /openfilesqueries/:
    get:
      description: This endpoint lists open files queries.
      operationId: openfilesqueries_list
      parameters:
      - description: Filter by path prefix substring
        in: query
        name: path_prefix__icontains
        schema:
          type: string
      - description: Filter by query name substring
        in: query
        name: name__icontains
        schema:
          type: string
      - description: Filter by tenant ID
        in: query
        name: tenant__id
        schema:
          type: integer
      - description: Filter queries created on or after date
        in: query
        name: created__gte
        schema:
          type: string
      - description: Filter queries created on or before date
        in: query
        name: created__lte
        schema:
          type: string
      - description: Filter by query state
        in: query
        name: state
        schema:
          type: string
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OpenFilesQuery'
                title: Open Files Queries
                type: array
          description: open files queries information
      summary: Get all open files queries.
      tags:
      - openfilesqueries
    post:
      description: This endpoint creates an open files query.
      operationId: openfilesqueries_create
      requestBody:
        $ref: '#/components/requestBodies/OpenFilesQueryParamsBody'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenFilesQueryWithAsyncTask'
          description: OK
      summary: Create an open files query.
      tags:
      - openfilesqueries
  /openfilesqueries/{id}/:
    delete:
      description: Delete an open files query.
      operationId: openfilesqueries_delete
      parameters:
      - $ref: '#/components/parameters/PathObjectId'
      responses:
        '204':
          description: OK
      summary: Delete an open files query.
      tags:
      - openfilesqueries
    get:
      description: This endpoint returns information about a specific open files query.
      operationId: openfilesqueries_read
      parameters:
      - $ref: '#/components/parameters/PathObjectId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenFilesQuery'
          description: ''
      summary: Return details of an open files query.
      tags:
      - openfilesqueries
components:
  requestBodies:
    OpenFilesQueryParamsBody:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/OpenFilesQueryParams'
      x-originalParamName: OpenFilesQueryParamsBody
  schemas:
    OpenFilesQueryWithAsyncTask:
      allOf:
      - $ref: '#/components/schemas/OpenFilesQuery'
      - $ref: '#/components/schemas/AsyncTaskInResponse'
    OpenFilesQuery:
      properties:
        async_task_id:
          description: Async task ID
          type: integer
        created:
          format: date-time
          type: string
          x-format: datetime2display
        filters:
          description: Filters used to create the query
          properties:
            return_only_locked_files:
              description: Whether to return only locked files
              type: boolean
          type: object
        guid:
          type: string
        id:
          type: integer
          x-cli-header: ID
        name:
          type: string
        path_prefix:
          description: Path prefix
          type: string
        state:
          description: State
          enum:
          - RUNNING
          - COMPLETED
          - PARTIALLY_COMPLETED
          - FAILED
          type: string
        tenant_id:
          type: integer
        title:
          type: string
        url:
          type: string
      type: object
      x-cli-pagination: true
    OpenFilesQueryParams:
      properties:
        filters:
          description: Filters to apply when creating the query
          type: object
        name:
          description: Open files query name
          type: string
        path_prefix:
          description: Path prefix
          type: string
        protocol:
          description: Protocol type
          enum:
          - SMB
          type: string
        tenant_id:
          description: Tenant ID
          type: integer
      required:
      - path_prefix
      - protocol
      type: object
    AsyncTaskInResponse:
      properties:
        async_task:
          description: Creation Async task properties
          type: object
      type: object
  parameters:
    PathObjectId:
      description: Object ID specified in the path
      in: path
      name: id
      required: true
      schema:
        type: string
    PageSize:
      in: query
      name: page_size
      schema:
        minimum: 1
        type: integer
    Page:
      in: query
      name: page
      schema:
        minimum: 1
        type: integer
  securitySchemes:
    ApiToken:
      description: Send current valid API token in an Authorization header with format Api-Token <token>.
      in: header
      name: ApiToken
      type: apiKey
    basicAuth:
      description: Basic authentication using VMS user name and password
      scheme: basic
      type: http
